spring.application.name=audit-document
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_document
spring.datasource.username=postgres
spring.datasource.password=franco

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true